// Perguntas transcritas do quiz original (v2.quizpablomarcal.com.br)
window.QUIZ_INTRO = {
  headline: 'NÃO É AZAR. É UM CICLO. E TODO CICLO PODE SER QUEBRADO.',
  sub: 'Faça o teste de 2 minutos, descubra quais dos **7 CICLOS** estão te prendendo e receba o plano exato pra quebrar cada ciclo.',
  genderQuestion: 'Para começar: você é...',
  options: [
    { value: 'homem', label: 'Homem', image: 'img/homem-cut.webp' },
    { value: 'mulher', label: 'Mulher', image: 'img/mulher-cut.webp' },
  ],
};

window.QUIZ_STEPS = [
  { id: 'idade', type: 'single', grid: 2, question: 'Qual a sua faixa de idade?', options: [
    { value: '18_29', label: '18 a 29 anos', emoji: '🧑' },
    { value: '30_39', label: '30 a 39 anos', emoji: '🧔' },
    { value: '40_49', label: '40 a 49 anos', emoji: '👨' },
    { value: '50_mais', label: '50 anos ou mais', emoji: '🧓' },
  ]},
  { id: 'familia', type: 'single', question: 'Você tem filhos?', options: [
    { value: 'sim', label: '👨‍👩‍👧 Sim' },
    { value: 'ainda_nao', label: '🙅 Ainda não' },
    { value: 'planejando', label: '🤰 Estou esperando / planejando' },
  ]},
  { id: 'rotina', type: 'single', question: 'No seu dia a dia hoje, você diria que a sua rotina é...', options: [
    { value: 'corrida', label: '🌀 Corrida, quase não paro' },
    { value: 'movimentada', label: '🕐 Movimentada, mas dou conta' },
    { value: 'tranquila', label: '🙂 Tranquila na maioria dos dias' },
    { value: 'parada', label: '😴 Meio parada, queria mais movimento' },
  ]},
  { id: 'fe', type: 'single', question: 'A sua fé faz parte da sua vida?', options: [
    { value: 'muito', label: '🙏 Sim, muito' },
    { value: 'mais_ou_menos', label: '✝️ Sim, mais ou menos' },
    { value: 'de_longe', label: '🤔 Acredito, mas de longe' },
    { value: 'nao_muito', label: '➖ Não muito' },
  ]},
  { id: 'financeiro', type: 'single', question: 'Sendo sincero(a), como está a sua vida financeira hoje?', options: [
    { value: '3', label: '😩 Endividado(a), no vermelho' },
    { value: '2', label: '😐 Fecho o mês, mas nunca sobra' },
    { value: '1', label: '🙂 Consigo guardar um pouco' },
    { value: '0', label: '💪 Tenho estabilidade, mas quero muito mais' },
  ]},
  { id: 'frequencia_dor', type: 'single', question: 'Com que frequência você tem a sensação de "de novo isso, sempre a mesma coisa"?', options: [
    { value: '3', label: '🔴 Quase todos os dias' },
    { value: '2', label: '🟠 Várias vezes por semana' },
    { value: '1', label: '🟡 De vez em quando' },
    { value: '0', label: '🟢 Raramente' },
  ]},
  { id: 'impacto_familia', type: 'single', question: 'Esse padrão que se repete já afetou as pessoas que você ama?', options: [
    { value: 'muito', label: '💔 Sim, e isso me machuca muito' },
    { value: 'escondo', label: '😟 Sim, mas tento esconder delas' },
    { value: 'pouco', label: '😕 Um pouco, ainda dá pra reverter' },
    { value: 'nunca_pensei', label: '🤐 Nunca parei pra pensar nisso' },
  ]},
  { id: 'padrao_travada', type: 'single', question: 'Quando você chega perto de uma virada de verdade, o que costuma acontecer?', options: [
    { value: 'da_errado', label: '🔁 Algo sempre dá errado na última hora' },
    { value: 'eu_travo', label: '😰 Eu mesmo(a) travo, adio, desisto' },
    { value: 'conta', label: '💸 Aparece uma conta / imprevisto que me joga pra trás' },
    { value: 'nao_pra_mim', label: '😶 Sinto que "não é pra mim" e recuo' },
  ]},
  { id: 'desejo_virada', type: 'single', question: 'Se você quebrasse esse ciclo hoje, o que mudaria de mais valioso na sua vida?', options: [
    { value: 'filhos', label: '👨‍👩‍👧 Deixar pros meus filhos uma história diferente da minha' },
    { value: 'sem_peso', label: '🕊️ Viver sem esse peso e essa culpa o tempo todo' },
    { value: 'prosperar', label: '💰 Prosperar sem sentir que estou fazendo algo errado' },
    { value: 'marco', label: '🌱 Ser lembrado(a) como quem virou o jogo da família' },
  ]},
  { id: 'rotina_futura', type: 'single', question: 'Imagine acordar daqui a 1 ano já livre desse padrão. Como seria o seu dia?', options: [
    { value: 'sem_aperto', label: '☀️ Sem aquele aperto no peito ao abrir as contas' },
    { value: 'paz', label: '😌 Com paz pra tomar decisões sem medo' },
    { value: 'crescer', label: '🚀 Focado(a) em crescer, não em sobreviver' },
    { value: 'presente', label: '❤️ Presente de verdade com quem eu amo' },
  ]},
  { id: 'prioridade_area', type: 'single', question: 'Se você pudesse destravar UMA área primeiro, qual seria?', options: [
    { value: 'financeira', label: '💵 A financeira, sair do aperto de vez' },
    { value: 'emocional', label: '🧠 A emocional, parar de me sabotar' },
    { value: 'fe', label: '🙏 A da fé, reconciliar prosperar e crer' },
    { value: 'relacional', label: '🤝 A dos relacionamentos, me cercar de gente que soma' },
  ]},
  { id: 'preferencia_caminho', type: 'single', question: 'E como você prefere alcançar essa virada?', options: [
    { value: 'passo_a_passo', label: '🗺️ Com um passo a passo claro, sem me perder' },
    { value: 'raiz', label: '🧩 Entendendo a raiz do problema, não só o sintoma' },
    { value: 'guia', label: '👊 Com alguém que já quebrou os próprios ciclos me guiando' },
    { value: 'rapido', label: '⚡ Do jeito mais rápido possível, sem enrolação' },
  ]},
  { id: 'areas_afetadas', type: 'multi', question: 'Selecione as áreas da sua vida que esse padrão invisível já afetou:', options: [
    { value: 'dinheiro', label: '💰 Dinheiro / prosperidade' },
    { value: 'familia', label: '👨‍👩‍👧 Família e filhos' },
    { value: 'amor', label: '❤️ Relacionamento amoroso' },
    { value: 'emocional', label: '🧠 Saúde emocional / autoestima' },
    { value: 'fe', label: '🙏 Fé e vida espiritual' },
    { value: 'carreira', label: '💼 Carreira / trabalho' },
  ]},
  { id: 'estado_atual', type: 'single', question: 'Sendo sincero(a) com você mesmo(a), hoje você está...', options: [
    { value: '3', label: '🆘 No modo sobrevivência, só apagando incêndio' },
    { value: '2', label: '🌫️ Perdido(a), sem saber por onde começar' },
    { value: '2b', score: 2, label: '🔄 Tentando, mas sempre voltando pra estaca zero' },
    { value: '0', label: '🎯 No controle, mas sei que posso muito mais' },
  ]},
  { id: 'vulnerabilidade', type: 'single', question: 'Quando você vê alguém da sua idade prosperando e quebrando ciclos, o que sente por dentro?', options: [
    { value: 'por_que', label: '😣 "Por que pra mim é sempre mais difícil?"' },
    { value: 'nao_nasci', label: '😔 "Talvez eu não tenha nascido pra isso"' },
    { value: 'sem_saber', label: '😤 Vontade de mudar, mas sem saber como' },
    { value: 'acostumei', label: '🙃 Já me acostumei, nem espero mais' },
  ]},
  { id: 'piloto_automatico', type: 'single', question: 'Você percebe que às vezes toma decisões "no automático", como se algo já estivesse decidido por você?', options: [
    { value: '3', label: '😳 Sim, o tempo todo, e me assusta' },
    { value: '2', label: '🤨 Sim, agora que você falou eu percebo' },
    { value: '1', label: '🙂 Às vezes' },
    { value: '0', label: '❓ Nunca tinha reparado' },
  ]},
  { id: 'crenca_prosperar', type: 'single', question: 'Quando o assunto é prosperar e crescer na vida, você se considera...', options: [
    { value: 'culpado', label: '😬 Alguém que se sente culpado(a) quando as coisas dão certo' },
    { value: 'espera_errado', label: '😟 Alguém que sempre espera que algo dê errado' },
    { value: 'nao_acredita', label: '🤞 Alguém que quer, mas não acredita totalmente' },
    { value: 'nao_sai', label: '💪 Alguém que acredita, mas não sai do lugar' },
  ]},
  { id: 'o_que_rouba', type: 'multi', question: 'O que esse ciclo mais rouba de você hoje?', options: [
    { value: 'liberdade', label: '🗽 Minha liberdade' },
    { value: 'tempo_familia', label: '👨‍👩‍👧 Tempo com minha família' },
    { value: 'proposito', label: '🎯 Meu propósito' },
    { value: 'alegria', label: '😊 Minha alegria' },
    { value: 'sonhos', label: '💭 Meus sonhos' },
    { value: 'prosperidade', label: '💰 Minha prosperidade' },
  ]},
  { id: 'revelacao_metodo', type: 'content', title: 'Uma coisa ficou clara.',
    body: 'Com base nas suas respostas até aqui: o seu problema não é falta de esforço, nem de fé, nem de capacidade. É um PADRÃO INVISÍVEL que nunca foi quebrado na sua linhagem.\n\nE é exatamente para isso que existe o QUEBRANDO CICLOS, o método de Pablo Marçal para identificar e romper os 7 ciclos que aprisionam uma família, para que você se torne o marco zero de uma nova geração.',
    quote: { author: 'Fernanda, (31) 9****-**08', text: 'eu jurava q meu problema era dinheiro. na vdd era a crença q eu tinha sobre dinheiro q meu pai me passou sem querer. quando isso caiu a ficha mudou tudo 🙌' } },
  { id: 'escala_culpa', type: 'scale', question: 'Avalie o quanto você concorda:', statement: 'No fundo, eu sinto que prosperar demais é errado ou perigoso.' },
  { id: 'escala_destino', type: 'scale', question: 'Avalie o quanto você concorda:', statement: 'Na minha família ninguém venceu de verdade, então é difícil acreditar que comigo será diferente.' },
  { id: 'autossabotagem', type: 'single', question: 'Você acredita que, mesmo sem querer, acaba se sabotando quando está perto de crescer?', options: [
    { value: '3', label: '😔 Sim, e já cansei de fazer isso comigo' },
    { value: '3b', score: 3, label: '😥 Sim, mas não consigo evitar' },
    { value: '1', label: '🤔 Às vezes desconfio que sim' },
    { value: '0', label: '🚫 Não, meu problema é só externo' },
  ]},
  { id: 'nao_dito_traicao', type: 'single', question: 'No fundo, uma parte de você sente que trair o padrão da família é uma espécie de traição a quem veio antes de você?', options: [
    { value: 'exato', label: '😶 Nossa... é exatamente isso' },
    { value: 'um_pouco', label: '😔 Um pouco, sim' },
    { value: 'faz_sentido', label: '🤔 Nunca tinha pensado, mas faz sentido' },
    { value: 'nao_sinto', label: '❌ Não sinto isso' },
  ]},
  { id: 'frases_herdadas', type: 'multi', question: 'Quais dessas frases você ouviu crescendo?', options: [
    { value: 'dinheiro_nao_traz', label: '💬 "Dinheiro não traz felicidade"' },
    { value: 'nao_nasceu_rico', label: '💬 "A gente não nasceu pra ser rico"' },
    { value: 'guarda', label: '💬 "Guarda que amanhã pode faltar"' },
    { value: 'ganancia', label: '💬 "Querer demais é ganância"' },
    { value: 'humilde_sofre', label: '💬 "Deus abençoa quem é humilde e sofre"' },
    { value: 'nao_sonha', label: '💬 "Não sonha alto pra não se decepcionar"' },
    { value: 'nao_pra_gente', label: '💬 "Isso não é pra gente como a gente"' },
    { value: 'nenhuma', label: '✖️ Nenhuma dessas' },
  ]},
  { id: 'autoridade_pablo', type: 'content', title: 'Cada frase que você marcou virou um comando dentro de você.',
    body: 'Você não escolheu essas crenças, elas foram instaladas antes de você entender o que era dinheiro, fé ou merecimento.\n\nO QUEBRANDO CICLOS foi criado por Pablo Marçal justamente para desinstalar esses comandos herdados, um a um, e reprogramar a forma como você decide.' },
  { id: 'custo_concreto', type: 'single', question: 'Por causa dessas crenças, você já deixou de fazer algo que poderia ter mudado sua vida?', options: [
    { value: 'recusei', label: '💔 Já recusei uma oportunidade por medo / por "não ser pra mim"' },
    { value: 'adiei', label: '⏳ Já adiei um sonho tantas vezes que quase desisti dele' },
    { value: 'nao_merecia', label: '😞 Já me convenci de que não merecia algo bom' },
    { value: 'prefiro_nao', label: '🤐 Prefiro nem lembrar dessas vezes' },
  ]},
  { id: 'julgamento_social', type: 'single', question: 'Você já se sentiu julgado(a) por querer mais do que sua família ou grupo acha "normal"?', options: [
    { value: 'familia', label: '👪 Sim, pela minha família' },
    { value: 'amigos', label: '👥 Sim, pelos meus amigos / grupo' },
    { value: 'todos', label: '🌐 Sim, por praticamente todos ao meu redor' },
    { value: 'apoio', label: '🙂 Não, tenho apoio' },
  ]},
  { id: 'origem_limites', type: 'multi', question: 'De onde você sente que esses limites mais vieram?', options: [
    { value: 'casa', label: '🏠 Da forma como fui criado(a) em casa' },
    { value: 'fe_sofrer', label: '🙏 De uma leitura de fé que ligava sofrer a ser bom' },
    { value: 'dinheiro_familia', label: '💸 Da relação da minha família com dinheiro' },
    { value: 'pessoas', label: '🗣️ Das pessoas com quem sempre convivi' },
    { value: 'lugar', label: '🌍 Do ambiente / lugar onde cresci' },
    { value: 'nunca_soube', label: '❓ Sinceramente, nunca soube de onde vinha' },
  ]},
  { id: 'voce_quebra', type: 'single', question: 'Olhando pra dentro agora: você acredita que VOCÊ pode ser a pessoa que quebra esse ciclo na sua família?', options: [
    { value: '0', label: '🔥 Sim, com certeza, é só eu descobrir como' },
    { value: '2', label: '🤞 Talvez, mas tenho muitas dúvidas' },
    { value: '3', label: '😞 Sinceramente, não acredito que consigo' },
  ]},
  { id: 'acolhimento_pessimista', type: 'content', title: 'Se você duvidou de si mesmo(a) agora, leia isto com atenção.',
    body: 'Muita gente que chegou até aqui pensava exatamente a mesma coisa, "não é pra mim". E foi justamente essa gente que mais mudou. Porque quem está completamente cansado do padrão é quem tem mais força pra rompê-lo.\n\nDuvidar não é o fim. É o último degrau antes da virada.' },
  { id: 'recaidas', type: 'single', question: 'Quantas vezes você já começou uma mudança animado(a) e voltou pro mesmo lugar?', options: [
    { value: 'muitas', label: '😩 Perdi as contas' },
    { value: '3_4', label: '😔 Umas 3 ou 4 vezes' },
    { value: '1_2', label: '😐 Uma ou duas' },
    { value: 'primeira', label: '🙂 Essa é a primeira vez que encaro isso de verdade' },
  ]},
  { id: 'tempo_virada', type: 'single', question: 'Se você tivesse um método que identifica e quebra os 7 ciclos, em quanto tempo você acredita que sua vida começaria a mudar?', options: [
    { value: '3', label: '🔥 Em semanas, eu só preciso do caminho certo' },
    { value: '2', label: '😊 Em poucos meses' },
    { value: '1', label: '😐 Talvez um ano' },
    { value: '0', label: '🙁 Sinceramente, acho que levaria anos' },
  ]},
  { id: 'maior_impedimento', type: 'single', question: 'Qual desses é hoje o seu MAIOR impedimento para quebrar o ciclo?', options: [
    { value: 'cultural', label: '🧠 As crenças herdadas que travam minhas decisões (Ciclo Cultural)' },
    { value: 'financeiro', label: '💰 O bloqueio com dinheiro e prosperidade (Ciclo Financeiro)' },
    { value: 'emocional', label: '😞 As feridas emocionais que viram sabotagem (Ciclo Emocional)' },
    { value: 'religioso', label: '🙏 A culpa de prosperar por causa da minha fé (Ciclo Religioso)' },
    { value: 'relacional', label: '🤝 O ambiente e as pessoas ao meu redor (Ciclo Relacional)' },
  ]},
  { id: 'calculando', type: 'loading', messages: [
    'Identificando os padrões herdados que se repetem em você...',
    'Cruzando suas respostas com os 7 ciclos invisíveis da sua família...',
    'Mapeando quais dos 7 ciclos ainda estão ativos em você...',
    'Comparando com 5.841 pessoas que também estão quebrando ciclos...',
  ]},
  { id: 'diagnostico_ciclos', type: 'diagnosis' },
  { id: 'compromisso_1', type: 'single', question: 'Agora que você viu seu diagnóstico, quão motivado(a) você está para quebrar esses ciclos de vez?', options: [
    { value: 'curioso', label: '🤔 Só estou curioso(a) pra entender melhor' },
    { value: 'quero_mas', label: '😔 Quero, mas ainda não sei se consigo' },
    { value: 'nao_paro', label: '🔥 Não vou parar até eu conseguir' },
  ]},
  { id: 'transicao_marco_zero', type: 'content', title: 'Essa decisão já é maior do que qualquer geração antes de você teve coragem de tomar.',
    body: 'A pergunta nunca foi "quem criou esse ciclo?".\n\nA pergunta é: "quem vai ter coragem de quebrá-lo?"\n\nDeixa eu te mostrar o que acontece quando alguém finalmente decide ser esse marco zero. 👇' },
  { id: 'comparativo', type: 'comparison' },
  { id: 'quebra_ja_tentei', type: 'content', title: 'O problema nunca foi você. Foi o ciclo que ninguém te ensinou a quebrar.',
    body: '"Eu já tentei mudar mil vezes e sempre voltei pro mesmo lugar."\n\nSe você pensou isso, preste atenção: você não voltou por falta de esforço. Você voltou porque estava tratando o SINTOMA (dinheiro, disciplina, motivação) enquanto o PADRÃO INVISÍVEL continuava intacto na raiz.\n\nEra muito esforço para pouco progresso.' },
  { id: 'quebra_sem_dinheiro', type: 'content', title: 'Quebrar o ciclo não é um gasto. É o que faz o resto parar de sangrar.',
    body: '"Mas eu não tenho dinheiro / tempo pra isso agora."\n\nEssa frase é o próprio ciclo falando por você. É o padrão de escassez tentando te manter exatamente onde está.\n\nPensa comigo: qual foi o custo de continuar preso(a) nesse ciclo pelos últimos 5, 10, 20 anos? Quanto ele já te tirou, em dinheiro, em paz, em oportunidades?' },
  { id: 'autoridade_transformacao', type: 'content', title: 'Não é só o bolso que muda. É a linhagem inteira.',
    body: 'Quando você quebra o padrão na raiz, o efeito se espalha: financeiro, emocional, relacional, espiritual. Porque era o mesmo padrão travando tudo.',
    quote: { author: 'Patrícia, (62) 9****-**59', text: 'em 6 meses: quitei o carro, voltei a orar em paz sem achar q dinheiro era pecado, e minha relação com meu marido melhorou demais. parece q destravou td junto 😭❤️' } },
  { id: 'compromisso_2', type: 'single', question: 'Você acredita que seria capaz de quebrar esse ciclo se tivesse o método e a direção certa?', options: [
    { value: 'pronto', label: '✅ Sim, estou pronto(a) pra isso' },
    { value: 'so_direcao', label: '🙂 Com certeza, só preciso de direção' },
    { value: 'quero_tentar', label: '🙁 Acho que sim... quero tentar' },
  ]},
  { id: 'compromisso_3', type: 'single', question: 'Última pergunta antes do seu plano: se essa fosse a sua chance real de mudar o sobrenome da sua família pra sempre, o que você diria?', options: [
    { value: 'marco_zero', label: '🔥 Chegou a minha vez. Eu vou ser o marco zero.' },
    { value: 'quebrar', label: '💪 Cansei de repetir. Quero quebrar esse ciclo.' },
    { value: 'muda_aqui', label: '🙏 Se depender de mim, minha história muda aqui.' },
  ]},
  { id: 'loading_final', type: 'loading', messages: [
    'Cruzando suas respostas com os 7 ciclos invisíveis…',
    'Comparando seu padrão com 5.841 pessoas quebrando ciclos...',
    'Identificando quais ciclos ainda comandam sua história...',
    'Sua análise está quase pronta…',
  ]},
  { id: 'captura_lead', type: 'lead' },
];

// Seções (progresso segmentado no topo, como no BetterMe)
window.QUIZ_SECTIONS = [
  { label: 'Meu perfil', start: 'idade' },
  { label: 'Meu ciclo', start: 'frequencia_dor' },
  { label: 'Meu caminho', start: 'preferencia_caminho' },
  { label: 'Crenças herdadas', start: 'escala_culpa' },
  { label: 'Minha virada', start: 'recaidas' },
  { label: 'Meu plano', start: 'compromisso_1' },
];

// Níveis do Índice de Ruptura (quanto maior a pontuação, mais preso ao ciclo)
window.QUIZ_LEVELS = {
  4: { name: 'Preso Profundo', range: 'nível 1 de 4', tone: 'danger', bar: 15,
    summary: 'Você está travado em padrões herdados que se repetem há gerações. O ciclo comanda suas decisões, e você ainda não teve as ferramentas certas pra romper. Reconhecer é o primeiro golpe, mas sozinho não basta.' },
  3: { name: 'Ciclo Ativo', range: 'nível 2 de 4', tone: 'danger', bar: 38,
    summary: 'Você já enxerga o ciclo, mas ele ainda dita o ritmo. Toda vez que tenta avançar, algo invisível te puxa de volta pro mesmo lugar. Falta método pra transformar consciência em ruptura real.' },
  2: { name: 'Rompendo com Esforço', range: 'nível 3 de 4', tone: 'warn', bar: 62,
    summary: 'Você luta contra o padrão todos os dias, e às vezes vence. Mas cada avanço custa energia demais, e a recaída sempre ronda. Sem estrutura, o ciclo volta a comandar quando você cansa.' },
  1: { name: 'Quase Livre', range: 'nível 4 de 4', tone: 'good', bar: 85,
    summary: 'Você chegou mais longe do que qualquer um da sua linhagem. Rompeu muito, mas ainda existe um passo a mais pra dar. A liberdade total exige método pra não recair e escala pra deixar legado.' },
};

window.QUIZ_PATTERNS = [
  { tag: 'Crença Central · Ciclo Cultural + Financeiro', name: 'Herança de Escassez',
    desc: 'Você foi programado(a) pra acreditar que "não é pra você", e decide a partir disso sem perceber.' },
  { tag: 'Sintoma Emocional · Ciclo Religioso + Financeiro', name: 'Culpa de Prosperar',
    desc: 'Toda vez que cresce, uma parte sua sente que está fazendo algo errado, e freia.' },
  { tag: 'Conflito Interno · Ciclo Parental + Relacional', name: 'Lealdade Invisível ao Passado',
    desc: 'Crescer soa como trair sua família. Então você repete o padrão pra continuar "pertencendo".' },
  { tag: 'Padrão de Comportamento · Ciclo Emocional', name: 'Autossabotagem Cíclica',
    desc: 'Perto da virada, você trava, adia ou desiste, sempre no mesmo ponto.' },
];

window.QUIZ_COMPARISON = [
  { label: 'Raiz do problema', a: 'Trata só o sintoma', b: 'Quebra o ciclo na raiz' },
  { label: 'Decisões', a: 'No automático herdado', b: 'Escolhidas por você' },
  { label: 'Dinheiro', a: 'Sempre volta a faltar', b: 'Para de sangrar' },
  { label: 'Recaída', a: 'Volta à estaca zero', b: 'Estrutura que sustenta' },
  { label: 'Sua família', a: 'Repete o mesmo padrão', b: 'Recebe uma história nova' },
];
